### ISSUE TITLE
False positives when using Cypress-axe

### ISSUE THREAD

**Issue by xthilakx** [avanslaars/cypress-axe#22] opened 2019-12-29 17:06 UTC
I started using `cypress-axe` to catch a11y issues when running end to end tests automatically, but I am finding it challenging to get the tests to pass. I get two errors which I believe are false positives: 
- page-has-heading-one
- landmark-one-main

I use [`react-axe`](https://github.com/dequelabs/react-axe), which prints a11y issues to browser console in development mode, but I don't see these two issues reported by that package. I tried auditing using [Axe Chrome extension](https://chrome.google.com/webstore/detail/axe-web-accessibility-tes/lhdoppojpmngadmnindnejefpokejbdd), but I do not see these. 

I would be happy to provide more information, but at this point, I believe it to be a bug with cypress-axe.

**Comment by tanya-harrys** [comment] 2020-01-22 18:01
Any update/response on this? I'm also getting these potential false positives.

**Comment by marcysutton** [comment] 2020-01-22 21:27
It would help to investigate which DOM nodes are failing with those rules in `cypress-axe`. Are those elements present in all the tests? That can help narrow down the test conditions leading to those results.

**Comment by tanya-harrys** [comment] 2020-01-23 14:26
Hey @marcysutton, so I'm running `cy.checkA11y()` over the entire document as soon as we visit the landing page and both the errors that @xthilakx reported appear on the `<html>` tag. 

I'm unable to see these errors using the [Axe Chrome Extension](https://chrome.google.com/webstore/detail/axe-web-accessibility-tes/lhdoppojpmngadmnindnejefpokejbdd) and have manually checked that there is only __one main landmark__ and __the landing page has a header one__ being rendered to the DOM.

**Comment by piemasters** [comment] 2020-01-23 20:39
I'm having the same issue. Everything worked fine until moving I moved over to using TypeScript with Cypress using webpack. 

For me the errors you've listed aren't false positives, it seems the scoping is off somehow as adding content that should trigger A11Y errors doesn't, you only ever get those two no matter what.

Sadly so far I've not found a fix either...

**Comment by piemasters** [comment] 2020-01-23 21:18
I moved over to using this and it all works ok for now: https://www.npmjs.com/package/better-cypress-axe

I'd rather not be dependant on it though. Having looked through the source I'm not fully sure what the 'fix' is compared to the setup recommended by others that I've used below:

cypress/plugins/index.js
```js 
const wp = require("@cypress/webpack-preprocessor");

module.exports = on => {
  const options = {
    webpackOptions: {
      resolve: {
        extensions: [".ts", ".tsx", ".js"]
      },
      module: {
        rules: [
          {
            test: /\.tsx?$/,
            loader: "ts-loader",
            options: { transpileOnly: true }
          }
        ]
      }
    }
  };
  on("file:preprocessor", wp(options));
};
```
cypress/support/commands.js
```js
import axe from "axe-core";
Cypress.Commands.add("injectAxe", () => {
  cy.window({ log: false }).then(window => {
    window.axe = axe;
  });
});
```
cypress/support/index.js
```js
import "cypress-axe";
import "./commands";
```
cypress/commands/index.d.ts
```ts
/// <reference types="cypress" />
declare namespace Cypress {
  interface Chainable {
    injectAxe(): Chainable<Element>;
    checkA11y(): Chainable<Element>;
  }
}
```
cypress/tsconfig.json
```json
{
  "compilerOptions": {
    "strict": true,
    "baseUrl": "../node_modules",
    "target": "es5",
    "lib": ["es5", "dom"],
    "types": ["cypress"],
    "typeRoots": ["./support"]
  },
  "include": ["**/*.ts"]
}
```
The test:
```ts
describe("Accessibility checks", () => {
  beforeEach(() => {
    cy.visit("/");
    cy.injectAxe();
    cy.wait(500);
  });
  it("Has no a11y violations", () => {
    cy.checkA11y();
  });
});
```

**Comment by tanya-harrys** [comment] 2020-01-24 11:42
I've also considered moving over to [better cypress axe](https://www.npmjs.com/package/better-cypress-axe), but would prefer not to. 
If it's working for you (for the time being at least) @piemasters then I'l give it a go until this has been resolved

**Comment by marcysutton** [comment] 2020-01-24 17:52
Maybe it's a timing issue with cypress-axe testing page content before it's fully loaded? I don't work on cypress-axe myself, but I used to be on the axe-core team and I maintain the cypress docs in Gatsby. So I have lots of ideas of things to try if you aren't getting a response from the maintainer!

Some things you could do to play around with it:
- Try adding an intentional violation to the h1 to see if it outputs a rule failure, like an invalid ARIA role (to check if that node is being evaluated at all)
- Try `cy.get('header')` or some other element that contains the h1 instead of `cy.wait` to see if anything changes with DOM readiness

Looks like better-cypress-axe bundles axe-core with it instead of a peer dependency, maybe it's related to an axe-core version? not sure.

**Comment by piemasters** [comment] 2020-01-30 10:53
Thanks for the reply @marcysutton! I finally had some time to look into this again. 

I added a few violations into a simple page with two headers and nope it's not getting evaluated. I replaced the wait with a get for a header on the page with the violation and it made no difference. I tried adding the get to before the `injectAxe()` call as well as after to see if that made any difference but sadly no. 

I tried using the same version of axe-core that better-cypress-axe uses (3.2.2) and no difference. I noticed better-cypress-axe is overriding the checkA11y command by calling `window.axe.run(...)`.

Could injectAxe and checkA11y be accessing different window instances somehow?

**Comment by GentlemanHal** [comment] 2020-02-12 22:37
After upgrading `axe-core` to `3.5.0` I started getting the `page-has-heading-one` violation, downgrading back to `3.4.1` stops the violation appearing.

My `cypress` version is `4.0.1` and `cypress-axe` version is `0.5.3`. I know v4 of cypress isn't officially on the peer dependency list but everything else seemed to be working before upgrading axe-core.

Aside:
Using the chrome extension doesn't have the violation but that is still using `axe-core 3.4.1`.

**Comment by JoshuaKGoldberg** [comment] 2020-03-28 19:47
@marcysutton unfortunately that's not it in my case. +1 to the "different window" theory. Simplifying source code here:

```ts
cy.window()
    .then(win => {
      const axe = (win.axe = require('axe-core'));
      console.log(
        'Axe is there with',
        win.document.body.innerHTML.includes('<h1')
          ? 'an h1 on the page'
          : 'no h1, oh no!'
      );

      return axe.run({ context: win });
    })
    .then(results => {
      console.log(results.violations.map(({ id }) => id));
    });
```

Logs:

```
Axe is there with an h1 on the page
tests?p=cypress/tests/portal/catalog.spec.ts-454:16565 (2) ["landmark-one-main", "page-has-heading-one"]
```

_(I've double-checked, and yes, the full page content is there - not just the `<h1`)_

This issue happens both with `axe.run()` and `axe.run({ context: ... })` set to `win`, `win.document`, or `win.document.body`,

**Comment by avanslaars** [comment] 2020-03-28 20:27
If somebody is able to provide a repo that reproduces the issue and/or try to reproduce with the latest (`0.7.0`) release of cypress axe, I can either close this issue or work to get to the bottom of the issue.

**Comment by JoshuaKGoldberg** [comment] 2020-03-28 21:43
Oh, `0.7.0` fixes it for me. Thanks so much!

**Comment by JoshuaKGoldberg** [comment] 2020-03-28 21:45
https://github.com/JoshuaKGoldberg/cypress-axe-repro

FWIW, `0.7.0` fixes it for me. Thanks so much! 🙌

**Comment by avanslaars** [comment] 2020-03-28 21:56
Thanks, @JoshuaKGoldberg for posting the repo for verification. I verified with default Cypress setup (using browserify as the preprocessor), as well as a setup with the webpack preprocessor (no TS). With your TS setup, it looks like this update covers the scenarios that seemed to be causing problems.

**Comment by tavelli** [comment] 2020-03-29 00:04
@avanslaars I was excited to read this so I bumped my repo version to 0.7.0 but still getting same false positives. Will create sample repo on Monday and share to reproduce. Running Cypress basic checkA11y on an angular app

**Comment by avanslaars** [comment] 2020-03-29 00:08
@tavelli sounds good, I’ll see what I can figure out with your sample when it’s available. Thanks!

**Comment by tavelli** [comment] 2020-03-30 14:25
@avanslaars when creating sample repo realized there was some extra config code i added earlier, it was suggested somewhere for typescript support. i removed that and now it works fine, no false positives 👍

**Comment by avanslaars** [comment] 2020-03-30 14:27
@tavelli Thanks for the update! Glad it's working for you now. Sounds like it's safe to close this one again :)

**Closed by avanslaars** 2020-03-30 14:27 UTC

**Comment by rowindatas25** [comment] 2020-12-28 19:45
Hi! I am having the same issue as others have reported here with the false positives: page-has-heading-one
landmark-one-main. Is there a definitive workaround for the solution? Or is it suggested to try better cypress axe?

Cypress version: 6.1
cypress-axe version: 0.12.0
